
package com.xdev.rapidclipse.demo.webservices.ui;

import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.WebTarget;

import org.glassfish.jersey.client.authentication.HttpAuthenticationFeature;

import com.google.gson.Gson;
import com.vaadin.server.FontAwesome;
import com.vaadin.shared.ui.MarginInfo;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.xdev.rapidclipse.demo.webservices.business.webservices.transferables.CustomerTransferable;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevHorizontalLayout;
import com.xdev.ui.XdevLabel;
import com.xdev.ui.XdevTextField;
import com.xdev.ui.XdevVerticalLayout;
import com.xdev.ui.XdevView;

public class MainView extends XdevView {

	private final String urlString = "http://localhost:8080/rapidclipse-demo-webservices/webservices/get/";

	/**
	 * 
	 */
	public MainView() {
		super();
		this.initUI();
	}

	/**
	 * Event handler delegate method for the {@link XdevButton}
	 * {@link #button2}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void button2_buttonClick(final Button.ClickEvent event) {
		final Client client = ClientBuilder.newClient();

		final WebTarget target = client.target(this.urlString + "customer/" + this.txtCustomerIDCall.getValue());
		final String response = target.request().get(String.class);

		final Gson gson = new Gson();
		final CustomerTransferable ct = gson.fromJson(response, CustomerTransferable.class);

		this.txtCustomerID.setValue(ct.getCustomerid());
		this.txtAddress.setValue(ct.getAddress());
		this.txtCity.setValue(ct.getCity());
		this.txtCompanyName.setValue(ct.getCompanyname());
		this.txtCountry.setValue(ct.getCountry());
		this.txtFax.setValue(ct.getFax());
		this.txtPhone.setValue(ct.getPhone());
		this.txtPLZ.setValue(ct.getPostalcode());
	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #button3}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void button3_buttonClick(final Button.ClickEvent event) {
		final HttpAuthenticationFeature token = HttpAuthenticationFeature.basic("admin", "admin");
		
		final Client client = ClientBuilder.newClient();
		client.register(token);

		final WebTarget target = client.target(this.urlString + "secure?name=" + this.txtToSend.getValue());
		final String response = target.request().get(String.class);
		
		this.txtResponse.setValue(response);
	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #button}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void button_buttonClick(final Button.ClickEvent event) {
		final Client client = ClientBuilder.newClient();

		final WebTarget target = client.target(this.urlString + this.txtToSend.getValue());
		final String response = target.request().get(String.class);
		
		this.txtResponse.setValue(response);
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.gridLayout = new XdevGridLayout();
		this.horizontalLayout3 = new XdevHorizontalLayout();
		this.verticalLayout2 = new XdevVerticalLayout();
		this.label2 = new XdevLabel();
		this.horizontalLayout = new XdevHorizontalLayout();
		this.txtToSend = new XdevTextField();
		this.button = new XdevButton();
		this.button3 = new XdevButton();
		this.txtResponse = new XdevTextField();
		this.verticalLayout3 = new XdevVerticalLayout();
		this.label3 = new XdevLabel();
		this.label4 = new XdevLabel();
		this.label5 = new XdevLabel();
		this.label7 = new XdevLabel();
		this.label = new XdevLabel();
		this.horizontalLayout2 = new XdevHorizontalLayout();
		this.txtCustomerIDCall = new XdevTextField();
		this.button2 = new XdevButton();
		this.verticalLayout = new XdevGridLayout();
		this.txtCustomerID = new XdevTextField();
		this.txtPLZ = new XdevTextField();
		this.txtCompanyName = new XdevTextField();
		this.txtCity = new XdevTextField();
		this.txtAddress = new XdevTextField();
		this.txtCountry = new XdevTextField();
		this.txtPhone = new XdevTextField();
		this.txtFax = new XdevTextField();
	
		this.horizontalLayout3.setMargin(new MarginInfo(false));
		this.verticalLayout2.setMargin(new MarginInfo(false));
		this.label2.setStyleName("h4");
		this.label2.setValue("Send a simple String");
		this.horizontalLayout.setMargin(new MarginInfo(false));
		this.txtToSend.setCaption("String to be send");
		this.txtToSend.setStyleName("small");
		this.button.setCaption("Send");
		this.button.setStyleName("small");
		this.button3.setIcon(FontAwesome.LOCK);
		this.button3.setCaption("Send secured");
		this.button3.setStyleName("small");
		this.txtResponse.setCaption("Server answered");
		this.txtResponse.setStyleName("small");
		this.verticalLayout3.setMargin(new MarginInfo(false));
		this.label3.setValue("Hints:");
		this.label4.setValue("1. This application has to be started by a Tomcat ");
		this.label5.setValue("2. Maybe it is necessary to change the URL which is used in the code.");
		this.label7.setValue(
				"3. For \"Send Secure\" with authentication it is necessary to enter the following line to the tomcat-user.xml -- <user username=\"admin\" password=\"admin\" roles=\"restconsumer\"/>");
		this.label.setStyleName("h4");
		this.label.setValue("Call an entity by ID");
		this.horizontalLayout2.setMargin(new MarginInfo(false));
		this.txtCustomerIDCall.setCaption("CustomerID (ALFKI, ANTON, ...)");
		this.txtCustomerIDCall.setStyleName("small");
		this.button2.setCaption("Laden");
		this.button2.setStyleName("small");
		this.verticalLayout.setMargin(new MarginInfo(false));
		this.txtCustomerID.setCaption("Kundennummer");
		this.txtCustomerID.setStyleName("small");
		this.txtPLZ.setCaption("Postleitzahl");
		this.txtPLZ.setStyleName("small");
		this.txtCompanyName.setCaption("Firmenname");
		this.txtCompanyName.setStyleName("small");
		this.txtCity.setCaption("Stadt");
		this.txtCity.setStyleName("small");
		this.txtAddress.setCaption("Adresse");
		this.txtAddress.setStyleName("small");
		this.txtCountry.setCaption("Land");
		this.txtCountry.setStyleName("small");
		this.txtPhone.setCaption("Telefon");
		this.txtPhone.setStyleName("small");
		this.txtFax.setCaption("Fax");
		this.txtFax.setStyleName("small");
	
		this.txtToSend.setWidth(100, Unit.PERCENTAGE);
		this.txtToSend.setHeight(-1, Unit.PIXELS);
		this.horizontalLayout.addComponent(this.txtToSend);
		this.horizontalLayout.setExpandRatio(this.txtToSend, 10.0F);
		this.button.setSizeUndefined();
		this.horizontalLayout.addComponent(this.button);
		this.horizontalLayout.setComponentAlignment(this.button, Alignment.BOTTOM_LEFT);
		this.button3.setSizeUndefined();
		this.horizontalLayout.addComponent(this.button3);
		this.horizontalLayout.setComponentAlignment(this.button3, Alignment.BOTTOM_CENTER);
		this.label2.setWidth(100, Unit.PERCENTAGE);
		this.label2.setHeight(-1, Unit.PIXELS);
		this.verticalLayout2.addComponent(this.label2);
		this.horizontalLayout.setWidth(100, Unit.PERCENTAGE);
		this.horizontalLayout.setHeight(-1, Unit.PIXELS);
		this.verticalLayout2.addComponent(this.horizontalLayout);
		this.txtResponse.setWidth(100, Unit.PERCENTAGE);
		this.txtResponse.setHeight(-1, Unit.PIXELS);
		this.verticalLayout2.addComponent(this.txtResponse);
		final CustomComponent verticalLayout2_spacer = new CustomComponent();
		verticalLayout2_spacer.setSizeFull();
		this.verticalLayout2.addComponent(verticalLayout2_spacer);
		this.verticalLayout2.setExpandRatio(verticalLayout2_spacer, 1.0F);
		this.label3.setSizeUndefined();
		this.verticalLayout3.addComponent(this.label3);
		this.verticalLayout3.setComponentAlignment(this.label3, Alignment.MIDDLE_LEFT);
		this.label4.setSizeUndefined();
		this.verticalLayout3.addComponent(this.label4);
		this.verticalLayout3.setComponentAlignment(this.label4, Alignment.MIDDLE_LEFT);
		this.label5.setSizeUndefined();
		this.verticalLayout3.addComponent(this.label5);
		this.verticalLayout3.setComponentAlignment(this.label5, Alignment.MIDDLE_LEFT);
		this.label7.setWidth(100, Unit.PERCENTAGE);
		this.label7.setHeight(-1, Unit.PIXELS);
		this.verticalLayout3.addComponent(this.label7);
		this.verticalLayout3.setComponentAlignment(this.label7, Alignment.MIDDLE_CENTER);
		this.verticalLayout2.setSizeFull();
		this.horizontalLayout3.addComponent(this.verticalLayout2);
		this.horizontalLayout3.setComponentAlignment(this.verticalLayout2, Alignment.MIDDLE_CENTER);
		this.horizontalLayout3.setExpandRatio(this.verticalLayout2, 10.0F);
		this.verticalLayout3.setWidth(100, Unit.PERCENTAGE);
		this.verticalLayout3.setHeight(-1, Unit.PIXELS);
		this.horizontalLayout3.addComponent(this.verticalLayout3);
		this.horizontalLayout3.setComponentAlignment(this.verticalLayout3, Alignment.MIDDLE_CENTER);
		this.horizontalLayout3.setExpandRatio(this.verticalLayout3, 10.0F);
		this.txtCustomerIDCall.setWidth(300, Unit.PIXELS);
		this.txtCustomerIDCall.setHeight(-1, Unit.PIXELS);
		this.horizontalLayout2.addComponent(this.txtCustomerIDCall);
		this.button2.setSizeUndefined();
		this.horizontalLayout2.addComponent(this.button2);
		this.horizontalLayout2.setComponentAlignment(this.button2, Alignment.BOTTOM_LEFT);
		final CustomComponent horizontalLayout2_spacer = new CustomComponent();
		horizontalLayout2_spacer.setSizeFull();
		this.horizontalLayout2.addComponent(horizontalLayout2_spacer);
		this.horizontalLayout2.setExpandRatio(horizontalLayout2_spacer, 1.0F);
		this.verticalLayout.setColumns(2);
		this.verticalLayout.setRows(5);
		this.txtCustomerID.setWidth(100, Unit.PERCENTAGE);
		this.txtCustomerID.setHeight(-1, Unit.PIXELS);
		this.verticalLayout.addComponent(this.txtCustomerID, 0, 0);
		this.txtPLZ.setWidth(100, Unit.PERCENTAGE);
		this.txtPLZ.setHeight(-1, Unit.PIXELS);
		this.verticalLayout.addComponent(this.txtPLZ, 1, 0);
		this.txtCompanyName.setWidth(100, Unit.PERCENTAGE);
		this.txtCompanyName.setHeight(-1, Unit.PIXELS);
		this.verticalLayout.addComponent(this.txtCompanyName, 0, 1);
		this.txtCity.setWidth(100, Unit.PERCENTAGE);
		this.txtCity.setHeight(-1, Unit.PIXELS);
		this.verticalLayout.addComponent(this.txtCity, 1, 1);
		this.txtAddress.setWidth(100, Unit.PERCENTAGE);
		this.txtAddress.setHeight(-1, Unit.PIXELS);
		this.verticalLayout.addComponent(this.txtAddress, 0, 2);
		this.txtCountry.setWidth(100, Unit.PERCENTAGE);
		this.txtCountry.setHeight(-1, Unit.PIXELS);
		this.verticalLayout.addComponent(this.txtCountry, 1, 2);
		this.txtPhone.setWidth(100, Unit.PERCENTAGE);
		this.txtPhone.setHeight(-1, Unit.PIXELS);
		this.verticalLayout.addComponent(this.txtPhone, 0, 3);
		this.txtFax.setWidth(100, Unit.PERCENTAGE);
		this.txtFax.setHeight(-1, Unit.PIXELS);
		this.verticalLayout.addComponent(this.txtFax, 1, 3);
		this.verticalLayout.setColumnExpandRatio(0, 10.0F);
		this.verticalLayout.setColumnExpandRatio(1, 10.0F);
		final CustomComponent verticalLayout_vSpacer = new CustomComponent();
		verticalLayout_vSpacer.setSizeFull();
		this.verticalLayout.addComponent(verticalLayout_vSpacer, 0, 4, 1, 4);
		this.verticalLayout.setRowExpandRatio(4, 1.0F);
		this.gridLayout.setColumns(1);
		this.gridLayout.setRows(4);
		this.horizontalLayout3.setWidth(100, Unit.PERCENTAGE);
		this.horizontalLayout3.setHeight(200, Unit.PIXELS);
		this.gridLayout.addComponent(this.horizontalLayout3, 0, 0);
		this.label.setSizeUndefined();
		this.gridLayout.addComponent(this.label, 0, 1);
		this.horizontalLayout2.setWidth(100, Unit.PERCENTAGE);
		this.horizontalLayout2.setHeight(-1, Unit.PIXELS);
		this.gridLayout.addComponent(this.horizontalLayout2, 0, 2);
		this.verticalLayout.setWidth(100, Unit.PERCENTAGE);
		this.verticalLayout.setHeight(-1, Unit.PIXELS);
		this.gridLayout.addComponent(this.verticalLayout, 0, 3);
		this.gridLayout.setColumnExpandRatio(0, 10.0F);
		this.gridLayout.setRowExpandRatio(3, 10.0F);
		this.gridLayout.setSizeFull();
		this.setContent(this.gridLayout);
		this.setSizeFull();
	
		this.button.addClickListener(event -> this.button_buttonClick(event));
		this.button3.addClickListener(event -> this.button3_buttonClick(event));
		this.button2.addClickListener(event -> this.button2_buttonClick(event));
	} // </generated-code>

	// <generated-code name="variables">
	private XdevLabel label2, label3, label4, label5, label7, label;
	private XdevButton button, button3, button2;
	private XdevHorizontalLayout horizontalLayout3, horizontalLayout, horizontalLayout2;
	private XdevGridLayout gridLayout, verticalLayout;
	private XdevTextField txtToSend, txtResponse, txtCustomerIDCall, txtCustomerID, txtPLZ,
			txtCompanyName, txtCity, txtAddress, txtCountry, txtPhone, txtFax;
	private XdevVerticalLayout verticalLayout2, verticalLayout3;
	// </generated-code>

}
